### PR TITLE
Re-port redraw fix and fix whitespace

### PR DESCRIPTION
**Pull request by zamaudio**
Signed-off-by: Damien Zammit <damien@zamaudio.com>

### CODE REVIEW

**Review by victoredwardocallaghan — COMMENTED** [review]
Well you don't need to touch the swapinterval() its more a hack for bad draw calling. What happens if you dont have it?

**Comment by zamaudio** [comment]
The swapinterval is good because all it does is wait until some drawing has changed between successive frames before bothering to flip.

**Comment by zamaudio** [comment]
its recommended to set it to 1, so prevents tearing

**Comment by zamaudio** [comment]
> Using a swap interval of zero can be useful for benchmarking purposes, when it is not desirable to measure the time it takes to wait for the vertical retrace. However, a swap interval of one lets you avoid tearing.

**Comment by victoredwardocallaghan** [comment]
I think that is more a documentation bug to make it "seem like" its recommend. It isn't recommend imho, here is why:

The GL drive puts the draw calls into a queue and does optimization there. Basically you are asking the GPU driver to do the equiv of mutex for every frame..

**Comment by victoredwardocallaghan** [comment]
tearing is a bug from X11, so what its _trying_ to say is that setting to one helps avoid some of the tearing that comes about because X11 is shit.

**Comment by zamaudio** [comment]
OK just drop that commit, it makes very little difference on my X11 anyway

**Pull request merged**
